def main() -> str:
    instructions = ('Please refer to the accompanying jupyter notebook'
                    ' where you will find an example of a named entity recognition'
                    ' model trained on data generated by putput.')
    return instructions

if __name__ == '__main__':
    print(main())
